### ISSUE TITLE
fails to build with ghc-9.6

### ISSUE THREAD

**Issue by juhp** [michalkonecny/mixed-types-num#5]
```
       Building library for mixed-types-num-0.5.11..                                                                                
       [ 1 of 24] Compiling Data.Convertible.Base                 
                                                                                                                                    
       /var/stackage/work/unpack-dir/unpacked/mixed-types-num-0.5.11-4964cc20935da519bedbcb8f61d873a04cc2ed0b4c212abfc0539aaab018f41
7/src/Data/Convertible/Base.hs:39:1: error:                                                                                         
           Could not find module ‘Control.Monad.Error’                                                                              
           Perhaps you meant                                                                                                                     Control.Monad.Co (needs flag -package-id kan-extensions-5.2.5)                                                         
             Control.Monad.Log (needs flag -package-id logging-effect-1.4.0)
             Control.Monad.Try (needs flag -package-id typecheck-plugin-nat-simple-0.1.0.9)  
           Use -v (or `:set -v` in ghci) to see a list of the files searched for.
          |                                                       
       39 | import Control.Monad.Error              
          | ^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by michalkonecny** [comment]
Fixed in version 0.5.12
